### ISSUE TITLE
How to handle Deadlocks

### ISSUE THREAD

**Issue by gawth** [johnnadratowski/golang-neo4j-bolt-driver#19] opened 2016-11-24 15:30 UTC
Hi,

firstly, library has worked really well - good piece of work.

I'm using it for a bit of load testing against a Neo4j instance and I'm getting a Neo.TransientError.Transaction.DeadlockDetected.  Looking around this is something that can occasionally happening if your repeatedly hitting the same nodes (which I am).

I'd like to handle it and then retry but can't figure out any (clean) way of checking the error response for Deadlocks.  At the moment I'm doing a strings.Contains for "Deadlock" on the error response string.

Thanks,
Alan

**Comment by johnnadratowski** [comment] 2016-12-15 16:29
@gawth - Sorry for the late response, I've been very busy in my personal life.

I'm happy you're enjoying the driver! It was a labor of love, I'm not using it for anything personally or professionally (yet!)

Error handling is one of the parts of this project which was difficult.  It wasn't always clear from the Neo4j Bolt docs nor the Golang sql driver docs how errors should be handled in all cases.  I just recently put through a PR to fix some issues with the error handling: https://github.com/johnnadratowski/golang-neo4j-bolt-driver/pull/20

Now, in terms of your specific case, if you could write up a test in a branch to reproduce this behavior, I can see if there is some way that makes sense for the driver to handle this better.  Right now, I don't think we get any specific "error code" from Neo4j, which it seems like is what you're looking for.  However, if I could see the behavior I can take a look at where/when it's happening to see if we have any extra data we can use to make the detection of this error easier.

If you look at the driver test file it is pretty simple to create a new test.  You just need a local Neo4j running and you can see the test command examples in the README.

**Comment by gawth** [comment] 2016-12-15 17:44
Thanks for the response, much appreciated.
I'll take a look next week although I've only seen it intermittently when my Neo4j cluster is under load so may be tricky to produce a test case.

With regards your point about error handling in the Bolt spec - I took a look at the .Net implementation to see if that offers any help (as its an official one).  Found [this](https://github.com/neo4j/neo4j-dotnet-driver/blob/9cb841a9bfc966ef45760c1e8902c9b0ca48a7af/Neo4j.Driver/Neo4j.Driver/Internal/PackStream/PackStreamMessageFormatV1.cs) that might be of help in understanding how the errors bubble out.

Ta
Alan

**Comment by johnnadratowski** [comment] 2016-12-15 19:06
@gawth - Thanks for the heads up here.  I see the main problem is that I'm essentially "eating" the failure message by turning it into an error.  I think I'm going to resolve this by making a new error type that will allow you to get failure message metadata.  That way you can explicitly check the code.  I'll start taking a look at this, and I'll see if I can reproduce it in a test.

**Comment by johnnadratowski** [comment] 2016-12-15 20:11
@gawth - I'd really like to get your feedback on this PR that exposes the internal failure message: https://github.com/johnnadratowski/golang-neo4j-bolt-driver/pull/22

Essentially, since I am wrapping the errors coming out, I was able to just make the FailureMessage match the `error` interface, and wrap it in the bolt errors I report.

To see how it's used, you can check out the `conn_test.go` file, and I also have a description of error handling I added to `doc.go` at the bottom of the file.

This would allow you to get the internal failure message metadata, and you can check the `code` directly.  Does that meet your need?

**Comment by johnnadratowski** [comment] 2016-12-15 20:14
@freeeve - I also saw you thumbs up'ed the issue.  Let me know what you think.

BTW - I'm a big fan of your `cq` driver which I've used quite a bit, and was a big inspiration for this library.

**Comment by johnnadratowski** [comment] 2016-12-17 19:56
@gawth - Let me know what you think of the implementation.  If you don't get a chance to give feedback I'll merge it, as I think it meets the need.

**Comment by iancmcc** [comment] 2016-12-19 22:57
If it helps, the PR exactly meets MY needs :) 👍

**Comment by johnnadratowski** [comment] 2016-12-20 21:52
@iancmcc - GOOD ENOUGH FOR ME! Merging now 🍠

**Comment by johnnadratowski** [comment] 2016-12-20 21:54
Since this PR does expose the internal failure message from Neo4J, and the original poster should be able to directly access the error code on the object, I'm closing this issue.  @gawth - if I missed something you can reopen it.

**Closed by johnnadratowski** 2016-12-20 21:54 UTC

**Comment by gawth** [comment] 2016-12-30 17:06
Sorry been distracted - works for me.
Ta,
Alan
